Add photo&content
codeklasse/codeklasse.de pull request #40
Opened 2022-01-20 23:56 UTC by tatosha

# Checkliste für neue Post
Checkliste mittels der _Live Preview_ abzuhacken:

- [ ] Rechtschreibung mit Copy+Paste in einem Checker geprüft
- [ ] Formattierung & Layout geprüft
- [ ] Sichtbarkeit des Posts geprüft
- [ ] Datum der Veröffentlichung in Dateinamen & Parameter geprüft
- [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
- [ ] [Bilder](https://resizeimage.net/) sind nicht größer als MAXIMAL 300kb & sehen trotzdem gut aus.
- [ ] Die obigen Punkte mit Hilfe der _Live Preview_ gecheckt
_
- [ ] Im Fall eines Blogartikels: Squash-Merge benutzen 

## Allgemeine Hinweise:
- codeklasse nicht Codeklasse
- Lehrkräfte statt Lehrer

2022-01-21 00:43 UTC, tatosha commented
@s-gbz bin dabei das Ganze mit dem Live Preview demnächst checken zu können. Wenn es nicht klappt, frage ich nach deinem Tipp. Erstmal probiere ich es doch selber aus, damit ich was daraus lernen kann. Schau mal bitte die Zeilen 45 und 86 an. Ich war mir da bei den Begriffen nicht sicher. Ich hoffe, dass es für dich kein Problem wird, die zu erweitern. In der Zeile 19, kannst du dich bestimmt besser beschreiben, als ich es getan habe:)

2022-01-24 07:14 UTC, s-gbz requested changes
Inhaltlich - siehe Signal :)

2022-01-24 07:19 UTC, s-gbz commented
Absätze wo ich keinen Refactoring-Bedarf sehe (good job on those!):
- Was war als Kind dein Lieblingsspielzeug?
- Wie sieht dein Arbeitsalltag aus 
- Was ist der nächste große Schritt?

Und ps: Saubere Commit message - sehr gut :relieved: Jetzt noch den Namen des Artikels im PR/ ersten Commit des branches & es ist perfekt :ok_hand:

2022-01-24 07:22 UTC, s-gbz commented on _posts/2022-01-21-interview-Sergej.md
> +Denkt lange nach… Keine Ahnung, ich habe keine Hürden gehabt, weil der Ruhrvalley Start-up-Campus, Grüße an Lenka, mir alle Fragen geklärt hatte.
```suggestion
[Denkt lange nach…] Keine Ahnung, ich habe keine Hürden gehabt, weil der <a class="is-underlined" href="https://www.rv-startupcampus.de/" target="_blank">Ruhrvalley Start-up-Campus</a>, Grüße an Lenka, mir alle Fragen geklärt hatte. 
```

2022-01-24 11:14 UTC, tatosha commented
@s-gbz ich arbeite noch an dem Bild. Es dauert aber nicht mehr lange. Ich wollte trotzdem, dass du schonmal den Blick auf den Text wirfst. Vielen Dank nochmal für deinen Input😊

2022-01-24 19:37 UTC, s-gbz approved these changes

2022-01-24 19:37 UTC, merged