Add "remove search query" icon/ button to blog search
codeklasse/codeklasse.de pull request #50
Opened 2022-01-28 20:26 UTC by seann1

# Checkliste für neue Post
Checkliste mittels der _Live Preview_ abzuhacken:

- [ ] Rechtschreibung mit Copy+Paste in einem Checker geprüft
- [ ] Formattierung & Layout geprüft
- [ ] Sichtbarkeit des Posts geprüft
- [ ] Datum der Veröffentlichung in Dateinamen & Parameter geprüft
- [ ] [Ein Satz pro Zeile](https://github.com/adessoAG/devblog/blob/master/examples/2017-08-10-blog-post-guide.md#ein-satz-pro-zeile)
- [ ] [Bilder](https://resizeimage.net/) sind nicht größer als MAXIMAL 300kb & sehen trotzdem gut aus.
- [ ] Die obigen Punkte mit Hilfe der _Live Preview_ gecheckt
_
- [ ] Im Fall eines Blogartikels: Squash-Merge benutzen 

## Allgemeine Hinweise:
- codeklasse nicht Codeklasse
- Lehrkräfte statt Lehrer

I have added the clear search functionality to the blog search bar. I used a fontawesome icon on the right of the search input which triggers the clear search function when clicked. I added the column search/categories layout at the same time. I hope this isn't a problem. I needed to add the fontawesome css file and webfonts folder to get the icon to align properly to the right of the search input.

2022-01-30 20:09 UTC, s-gbz requested changes
Hey there Sean, sorry for the late-ish reply and thanks for your PR  :100: .
Please try to avoid commits to the Gem- & lock.file, because it messes with the netlify build.
You can do that by only staging specific files like `blog.html` in our case.

Our first follow up task would be to hence remove the changes to `Gemfile.lock`.
This also goes for all new fontawesome files, because they tend to be unnecessary weight to the build since we only use a couple of icons.

You can however add your desired icon via svg.
[Here's](https://github.com/codeklasse/codeklasse.de/blob/bcc605a652b37b94d4328751c8ea3805adc5a19a/_includes/footer.html#L35) an example how you can do that. It will blend in seamlessly, just make sure to give it a width as seen in the example.

I will provide final technical feedback after the requested changes if you don't mind.
As again, let me know if there's anything I can provide you and rock on :rocket: :relaxed:

2022-01-31 15:46 UTC, s-gbz commented on blog.html
> +        });
```suggestion
        elems.forEach(el => {
            el.classList.remove("hidden");
        });
```

2022-01-31 15:47 UTC, s-gbz commented on blog.html
> +        elems.forEach(el => {
```suggestion
        const hiddenPosts = document.querySelectorAll(".hidden");
        hiddenPosts.forEach(el => {
```

2022-01-31 15:53 UTC, s-gbz approved these changes
I improved the naming & used a fat arrow function.
Other than that thanks for helping out @seann1 - the layout works really fine!

2022-01-31 15:53 UTC, merged

2022-01-31 15:57 UTC, s-gbz commented
Juuuuuuuuust in case you happened to be bored, there is a very last blog related issue #30
As always, feel free to ignore it and have a wonderful week! :sun_with_face: 
All the best from Germany :beers:

2022-02-01 00:40 UTC, seann1 commented
Thanks, and thanks for the help!